export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_WAITING_LIST = 'FETCH_WAITING_LIST';
export const DISPLAY_PRODUCTS = 'DISPLAY_PRODUCTS';
export const LOAD_MORE_PRODUCTS = 'LOAD_MORE_PRODUCTS';

